### ISSUE TITLE
Change DevSecOps Github Actions workflow to only run on main and tags

### ISSUE THREAD

**Issue by timbastin** [l3montree-dev/flawfix#41]
I think this should be sufficient inside the `.github/devsecops.yaml`

```yaml
on:
  push:
    branches:
      - main
    tags:
      - '*'
```
